# Project information
site_name: MedSus
site_author: Grupo 05
site_url: https://Requisitos-de-Software.github.io/2021.2-MedSUS

# Repository
repo_name: 2021.2-MedSUS
repo_url: https://github.com/Requisitos-de-Software/2021.2-MedSUS

theme:
  name: 'material'
  language: 'pt'
  logo: 'assets/logo_medsus.png'
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: 'Montserrat'
    code: 'sans-serif'

extra_css:
  - extra.css

# Content Menu
nav:
  - Início: index.md
  - Planejamento:
    - Metodologia: about/methodology.md
    - Ferramentas: about/tools.md
    - Cronograma: about/planning.md
  - Pré-Rastriabilidade:
    - Rich Picture: pre_traceability/rich_picture.md
    - 5W2H: pre_traceability/5w2h.md
  - Elicitação:
    - Brainstorm: elicitation/brainstorm.md
    - Storytelling: elicitation/storytelling.md
    - Personas: elicitation/personas.md
    - Instrospecção: elicitation/introspective.md
  - Priorização: priorization/moscow.md
  - Apresentações:
      - Apresentação 1: presentations/presentation1.md
