# Project information
site_name: MedSus
site_author: Grupo 05
site_url: https://Requisitos-de-Software.github.io/2021.2-MedSUS

# Repository
repo_name: 2021.2-MedSUS
repo_url: https://github.com/Requisitos-de-Software/2021.2-MedSUS

# Content Menu
nav:
    - Home: index.md
    - Planejamento: about/planning.md
    - About:
      - Equipe: about/authors.md
      - Ferramentas: about/tools.md
      - Metodologia: about/methodology.md
    - Pr√©-rastreabilidade:
      - Rich Picture: pre_traceability/rich_picture.md

theme: readthedocs
extra_css: [extra.css]
