# Project information
site_name: MedSUS
site_author: Grupo 05
site_url: https://Requisitos-de-Software.github.io/2021.2-MedSUS

# Repository
repo_name: 2021.2-MedSUS
repo_url: https://github.com/Requisitos-de-Software/2021.2-MedSUS

theme:
  name: "material"
  language: "pt"
  logo: "assets/logo_medsus.png"
  palette:
    primary: "blue"
    accent: "light blue"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - extra.css

plugins:
  - mkdocs-video

# Content Menu
nav:
  - Início: index.md
  - Planejamento:
      - Metodologia: about/methodology.md
      - Ferramentas: about/tools.md
      - Cronograma: about/planning.md
  - Pré-Rastreabilidade:
      - Rich Picture: pre_traceability/rich_picture.md
      - 5W2H: pre_traceability/5w2h.md
  - Elicitação:
      - Brainstorm: elicitation/brainstorm.md
      - Personas: elicitation/personas.md
      - Storytelling: elicitation/storytelling.md
      - Instrospecção: elicitation/introspective.md
  - Priorização:
      - MoscoW: priorization/moscow.md
      - First Things First: priorization/first_things_first.md
  - Modelagem:
      - Léxicos: modeling/lexicos.md
      - Casos de Uso: modeling/usecase.md
      - Cenários: modeling/scenarios.md
      - Especificação Suplementar: modeling/supplementary_specification.md
      - Backlog: modeling/product_backlog.md
      - História de usuário: modeling/userstory.md
      - NFR: modeling/nfr.md
  - Análise:
      - Verificação:
          - Explicação: verification/verification.md
          - Cenários: verification/inspection_scenarios.md
          - NFR: verification/inspection_nfr.md
          - Backlog: verification/inspection_backlog.md
          - Léxico: verification/inspection_lexicon.md
          - Rich Picture: verification/inspection_richpicture.md
          - Especificação Suplementar: verification/inspection_suplementary.md
          - Casos de Uso: verification/inspection_usecase.md
          - Forward from: verification/forward_from.md
      - Validação: validation/prototyping.md
  - Pós Rastreabilidade:
      - Backward from: post_traceability/backward_from.md
      - Forward from: post_traceability/forward_from.md
  - Apresentações:
      - Apresentação 1: presentations/presentation1.md
      - Apresentação 2: presentations/presentation2.md
      - Apresentação 3: presentations/presentation3.md
      - Apresentação 4: presentations/presentation4.md
      - Apresentação 5: presentations/presentation5.md
      - Apresentação 6: presentations/presentation6.md
      - Apresentação Final: presentations/finalpresentation.md
